name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DEVELOPER_DIR: /Applications/Xcode_13.2.app

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
      with:
        swift-version: "5.6.0"
    - name: Build
      run: swift build -v

  test:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
      with:
        swift-version: "5.6.0"
    - name: Test
      run: swift test -v
